debug: true

spring:
  application:
    name: openehr-community-server

  datasource:
    url: jdbc:postgresql://postgres:5432/ehrbase
    username: ehrbase
    password: ehrbase
    hikari:
      driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://postgres:5432/ehrbase
    user: ehrbase
    password: ehrbase

management:
  metrics:
    distribution:
      percentiles:
        all: 0.5, 0.90, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}
  server:
    port: 7979
  endpoints:
    web:
      exposure:
        include: '*'
